import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";

const spaceGrotesk = Space_Grotesk({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata: Metadata = {
  metadataBase: new URL("http://localhost:3000"),

  title: "Portfolio Aceternity UI",
  authors: {
    name: "rizqinoorfauzan",
  },

  description:
    "Based in Indonesia, I'm a Fullstack developer passionate aboutbuilding a modern web application that users love.",
  openGraph: {
    title: "Portfolio ",
    description:
      "Based in Indonesia, I'm a Fullstack developer passionate aboutbuilding a modern web application that users love.",
    url: "http://localhost:3000",
    siteName: "Daily vote",
    images: "/og.png",
    type: "website",
  },
  keywords: ["rizqinoorfauzan", "portfolio", "dailywebcoding"],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={spaceGrotesk.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
